name: 'Mypy action'
github-token:
  environment-variable-name: GITHUB_TOKEN
    is-default: false
  permissions:
    checks: write
    checks- reasons: to create checks and update
    #Reference:https://github.com/sasanquaneuf/mypy-github-action/blob/8908b8f82282257ad047399601892ba0f91afd9a/src/main.ts#L67
    #1278
